version: '3.8'

services:
  # 后端服务 - 连接外部数据库
  backend:
    image: 040317/pose-gallery-backend:main
    # 使用host网络模式以便访问外部数据库
    network_mode: "host"
    environment:
      # 外部数据库配置
      - DB_HOST=${EXTERNAL_DB_HOST}
      - DB_PORT=${EXTERNAL_DB_PORT:-3306}
      - DB_USER=${EXTERNAL_DB_USER}
      - DB_PASS=${EXTERNAL_DB_PASS}
      - DB_NAME=${EXTERNAL_DB_NAME}
      
      # 外部Redis配置
      - REDIS_HOST=${EXTERNAL_REDIS_HOST}
      - REDIS_PORT=${EXTERNAL_REDIS_PORT:-6379}
      - REDIS_PASSWORD=${EXTERNAL_REDIS_PASSWORD}
      - REDIS_DB=${EXTERNAL_REDIS_DB:-0}
      
      # 其他配置
      - OSS_ENDPOINT=${OSS_ENDPOINT}
      - OSS_ACCESS_KEY=${OSS_ACCESS_KEY}
      - OSS_SECRET_KEY=${OSS_SECRET_KEY}
      - OSS_BUCKET=${OSS_BUCKET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4-vision-preview}
      
      # 绑定到所有接口以便前端访问
      - HOST=0.0.0.0
      - PORT=8000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # 前端服务
  frontend:
    image: 040317/pose-gallery-frontend:main
    # 使用host网络模式，自动绑定到主机的3000端口
    network_mode: "host"
    # 移除ports配置，因为host网络模式下不需要端口映射
    environment:
      # 在host网络中可以直接使用localhost
      - NEXT_PUBLIC_API_URL=http://127.0.0.1:8000
      - BACKEND_URL=http://127.0.0.1:8000
      # 强制绑定到所有网络接口，忽略主机名
      - HOSTNAME=0.0.0.0
      - PORT=3000
      
      # Next.js 特定配置
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3